#!/bin/sh

cd $HOME

tmux rename-window 'Backend'

# Create new tmux pane
# Run something
tmux split-window -d -v
tmux send-keys -t 1 'cd $HOME/work/SOMETHING' Enter

# Create new tmux pane
# Run something
tmux split-window -d -h
tmux send-keys -t 1 'cd $HOME/work/SOMETHING' Enter

# Run something
tmux send-keys 'cd $HOME/work/SOMETHING' Enter

# Open new window
# Run something
tmux new-window -n 'Frontend'
tmux send-keys -t '0:1' 'cd $HOME/work/SOMETHING' Enter

# Select frontend window
# Split window
# Select bottom pane
# go to fronendt repo
tmux select-window -t '0:1'
tmux split-window -d -v -t 'Frontend'
tmux select-pane -t 1
tmux send-keys -t '0:1' 'cd $HOME/work/SOMETHING' Enter


# if you want to know the pane you are in 
# tmux display -pt "${TMUX_PANE:?}" '#{pane_index}'
